javascript:(function(){function CPCColorChanger(){ ICC=window.frames[0].document.createElement('input');
       ICC.type='color';
       ICC.style.marginRight='3px';
       ICC.value=localStorage.getItem('lastCPCColor') ?? '#ffe793';
       ICN=window.frames[0].document.createElement('input');
       ICN.type='number';
       ICN.value=1;
       ICN.style.width='45px';
       ICN.style.height='25px';
       ICN.style.marginRight='3px';
       ICB=window.frames[0].document.createElement('input');
       ICB.type='button';
       ICB.value='Einfärben';
       ICB.ID='ICB';
       ICB.style.marginRight='3px';
       ICB.style.padding='5px';
       ICB.style.height='25px';
       ICD=window.frames[0].document.createElement('input');
       ICD.type='button';
       ICD.value='Reset all';
       ICD.ID='ICD';
       ICD.style.marginRight='3px';
       ICD.style.padding='5px';
       ICD.style.height='25px';
       CCN=window.frames[0].document.createElement('canvas');
       CCN.ID='preSetColors';
       CCN.setAttribute('style','marginRight:3px;
       width:200;
       height:200;
       border:1px solid black;
       ');
       /*MODULE_BEGIN:lazymouse       Description: lazymouse,lazyMouseClick, _clickTargert & _toggleDefaultClickBehavior_Btn deaktivieren das typische Mausverhalten*/       _toggleDefaultClickBehavior_Btn=document.createElement('input');
       _toggleDefaultClickBehavior_Btn.type='checkbox';
       _toggleDefaultClickBehavior_Btn.title='State:CHECKED- classes can be copied. State:UNCHECKED - back to default behavior of espacenet';
       colorChangeContainer=window.frames[0].document.createElement('div');
       colorChangeContainer.appendChild(ICC);
       colorChangeContainer.appendChild(ICN);
       colorChangeContainer.appendChild(ICB);
       colorChangeContainer.appendChild(ICD);
       colorChangeContainer.appendChild(_toggleDefaultClickBehavior_Btn);
       colorChangeContainer.setAttribute('style','box-shadow:1px 0px 2px 0px #000000;
       display:inline-flex;
       padding:3px');
       window.frames[0].document.querySelector('#cpcbrowser > div.cpcbrowser-header > ul > li:nth-child(7)').insertAdjacentElement('afterend',colorChangeContainer);
       ICB.addEventListener('click',changeLevelColor,0);
       ICD.addEventListener('click',resetAllColors,0);
              var lazymouse=function(){event.stopPropagation()};
       lazyMouseClick='true';
       _clickTarget=window.frames[0].document.querySelector('#cpcbrowser > div.cpcbrowser-results-holder.show-references.show-2000-series');
       _toggleDefaultClickBehavior_Btn.addEventListener('change',function(){        if (lazyMouseClick) {_clickTarget.addEventListener('click',lazymouse,true);
console.log('default clicking behavior DEACTIVATED')}         else {_clickTarget.removeEventListener('click',lazymouse,true);
 console.log('default clicking behavior ACTIVATED')};
        lazyMouseClick=!lazyMouseClick});
       /*MODULE_END:lazymouse*/              function changeLevelColor(){ _level=ICN.value;
       _selector='tr.level-'+(_level-1+Number(window.frames[0].document.querySelectorAll('tr[class*=level]')[0].getAttribute('level')));
       _rule=ICC.value;
       _rule='background-color:'+_rule+'!important';
       [...window.frames[0].document.querySelectorAll(`${_selector}`)].forEach(i=>i.setAttribute('style',`${_rule}`));
       localStorage.setItem('lastCPCColor', ICC.value);
       /*Remember last Color*/ localStorage.setItem('lastCPCSelector', _selector);
       /*Remember last Selector*/ };
       function resetAllColors(){ for (i=1;
       i<8;
       i++){ _selector='tr.level-'+(i-1+Number(window.frames[0].document.querySelectorAll('tr[class*=level]')[0].getAttribute('level')));
       [...window.frames[0].document.querySelectorAll(_selector)].forEach(i=>i.setAttribute('style','background-color:white!important'));
       };
       };
       };
   CPCColorChanger();
 }())
